# pyproject.toml
[build-system]
requires = [
  "setuptools>=80.0",
  "wheel",
  "pybind11",
  "numpy>=1.20"       # needed for numpy.get_include()
]
build-backend = "setuptools.build_meta"

[project]
name = "i_plus_one"
version = "0.1.0"
description = "Language Learning App"
requires-python = ">=3.12"
# your runtime deps:
dependencies = ["numpy>=1.20"]

# tell setuptools to find your packages
[tool.setuptools.packages.find]
where = ["."]
include = ["i_plus_one"]

[tool.cibuildwheel]
# Build only for Python 3.12
build = "cp312-*"

# Linux aarch64 build
[tool.cibuildwheel.linux]
build = "cp312-manylinux_2_28*"
archs = ["aarch64"]